meta_product_name: "Julia Frederico - Articles"
meta_title: "Julia Frederico - Thoughts on Design and Art"
meta_description: "As a communicator, I've always been interested with the possibility of taking two steps back and understanding the context in which each story and discourse is created and scattered. Whenever I'm working on a multidisciplinary project, my work translates this effort of analyzing where we stand socially and culturally."
meta_image: "cover.png"
